[package]
name = "kubectl-split_config"
version = "0.0.0-0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5", features = ["derive"] }
saphyr = "0.0.3"
